version: "3.9"
services:
  backend:
    build:
      context: ./status-display-app-backend
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./status-display-app-frontend
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - backend

  kiosk:
    build:
      context: ./vnc-kiosk-server-custom
    networks:
      - app-network
    ports:
      - "5901:5900"
    environment:
      - URL=http://frontend
      - TZ=Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - frontend
      - backend
    privileged: true

networks:
  app-network:
    driver: bridge
